rm -f Documentation/filesystems/cifs/winucase_convert.pl 
rm -f drivers/staging/lustre/lustre/include/lustre_dlm_flags.h 
rm -f drivers/marvell/sd8897/wlan_src/gpl-2.0.txt 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sta_ioctl.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_join.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_uap_cmdevent.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11h.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sdio.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_meas.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_module.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_ieee.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sta_tx.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11n_aggr.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_uap_txrx.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11n_rxreorder.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_misc.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sta_cmdresp.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11ac.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sdio.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_main.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_shim.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_decl.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_meas.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_ioctl.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sta_event.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11n.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_uap_ioctl.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11ac.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_txrx.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_wmm.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_fw.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_cfp.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11n_rxreorder.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_uap.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_init.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11d.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_wmm.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11h.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11n.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_init.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sta_rx.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_sta_cmd.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_cmdevt.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_scan.c 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_join.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_util.h 
rm -f drivers/marvell/sd8897/wlan_src/mlan/mlan_11n_aggr.h 
rm -f drivers/marvell/graphics/driver/hal/makefile.linux 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_command.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/makefile.linux 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_interrupt_vg.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_power.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel.h 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_precomp.h 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_heap.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_vg.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_mmu_vg.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/arch/makefile.linux 
rm -f drivers/marvell/graphics/driver/hal/kernel/arch/gc_hal_kernel_context.h 
rm -f drivers/marvell/graphics/driver/hal/kernel/arch/gc_hal_kernel_hardware.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/arch/gc_hal_kernel_context.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/arch/gc_hal_kernel_recorder.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/arch/gc_hal_kernel_hardware.h 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_security.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_vg.h 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_db.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_debug.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_video_memory.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_buffer.h 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_command_vg.c 
rm -f drivers/marvell/graphics/driver/hal/kernel/gc_hal_kernel_mmu.c 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_platform.h 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/allocator/default/gc_hal_kernel_allocator_array.h 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_security_channel.c 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_device.h 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/platform/default/gc_hal_kernel_platform_default.c 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_debugfs.c 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_allocator.h 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_device.c 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_linux.c 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_sync.h 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_debug.h 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_math.c 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_allocator.c 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_os.h 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_sync.c 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_debugfs.h 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_os.c 
rm -f drivers/marvell/graphics/driver/hal/os/linux/kernel/gc_hal_kernel_linux.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_security_interface.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_types.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_version.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_driver.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_options.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_engine_vg.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_statistics.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_mem.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_dump.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_rename.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_options_mrvl.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_base.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_profiler.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_engine.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_cl.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_raster.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_driver_vg.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_vg.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_enum.h 
rm -f drivers/marvell/graphics/driver/hal/inc/gc_hal_eglplatform.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sta_ioctl.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_join.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_uap_cmdevent.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_11h.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sdio.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_meas.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_module.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_ieee.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sta_tx.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_11n_aggr.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_uap_txrx.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_11n_rxreorder.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_misc.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sta_cmdresp.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sdio.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_main.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_shim.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_decl.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_meas.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_ioctl.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sta_event.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_11n.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_uap_ioctl.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_txrx.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_wmm.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_cfp.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_11n_rxreorder.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_uap.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_init.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_11d.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_wmm.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_11n.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_init.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sta_rx.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_sta_cmd.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_cmdevt.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_scan.c 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_join.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_util.h 
rm -f drivers/marvell/sd8787/wlan_src/mlan/mlan_11n_aggr.h 
rm -f include/linux/sensor/yas_android_lib.h 
rm -f include/linux/i2c/mc3xxx.h 
rm -f drivers/hwmon/mc3xxx.c 